  language: "en-US"
  tone_instructions: "Be concise. Focus on bugs, security, and performance. Skip style nits."

  reviews:
    auto_review:
      enabled: true
      drafts: false
      base_branches:
        - "main"
    request_changes_workflow: true
    high_level_summary: true
    walkthrough: true
    poem: false
    path_filters:
      - "!dist/**"
      - "!**/*.lock"
      - "!**/generated/**"
    path_instructions:
      - path: "src/api/**"
        instructions: "Focus on security and error handling"
      - path: "src/components/**"
        instructions: "Check for accessibility issues"

  chat:
    auto_reply: true

  tools:
    eslint:
      enabled: true
    gitleaks:
      enabled: true