language: "en-US"

reviews:
  tone_instructions: >
    Be concise and actionable. Prioritize in this order:
    1. Bugs, logic errors, and potential runtime failures.
    2. Security vulnerabilities (injection, auth bypass, data exposure).
    3. Performance anti-patterns (N+1 queries, unnecessary re-renders, blocking calls in loops, unbounded data fetches).
    4. Race conditions and concurrency issues.
    5. Code conflicts or inconsistencies with existing patterns in the codebase.
    6. Readability — if code is unnecessarily complex, suggest a simpler alternative with a brief code snippet. Do not nitpick formatting or style that linters already catch.
    Always explain *why* something is a problem, not just *what* to change.
    When suggesting a fix, provide a concrete code example.
    Skip praise and filler — only comment when there is something to improve.
  auto_review:
    enabled: true
    drafts: false
    base_branches:
      - "main"
  request_changes_workflow: true
  high_level_summary: true
  walkthrough: true
  poem: false
  path_filters:
    - "!dist/**"
    - "!**/*.lock"
    - "!**/generated/**"
  path_instructions:
    - path: "src/api/**"
      instructions: "Focus on security and error handling"
    - path: "src/components/**"
      instructions: "Check for accessibility issues"

chat:
  auto_reply: true

tools:
  eslint:
    enabled: true
  gitleaks:
    enabled: true
